crewverve/models.py
from typing import Self
import bcrypt
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def init_app(app):
   db.init_app(app)
   return db

class User(db.Model):
    id_user = db.Column(db.Integer, primary_key=True)
    name_user = db.Column(db.String(255), nullable=False, unique=True)
    email_user = db.Column(db.String(255), nullable=False, unique=True)
    password_hash = db.Column(db.String(128), nullable=False)
    password_salt = db.Column(db.String(128), nullable=False)
    projects = db.relationship('Project', secondary='user_project', back_populates='users')

    def set_password(self, password):
        # Generate a random salt
        salt = bcrypt.gensalt()

        # Hash the password using the salt and the bcrypt algorithm
        password_hash = bcrypt.hashpw(password.encode('utf-8'), salt)

        # Store the salt and the hashed password in the database
        self.password_salt = salt.decode('utf-8')
        self.password_hash = password_hash.decode('utf-8')

    def check_password(self, password):
        # Hash the password using the stored salt and the bcrypt algorithm
        password_hash = bcrypt.hashpw(password.encode('utf-8'), self.password_salt.encode('utf-8'))

        # Compare the hashed password to the stored password hash
        return password_hash == self.password_hash.encode('utf-8')
    
    
class Project(db.Model):
    id_project = db.Column(db.Integer, primary_key=True)
    name_project = db.Column(db.String(255), nullable=False)
    # para hacer 1-n entre proyecto y encuesta
    surveys = db.relationship('Survey', backref='project')
    #surveys = db.relationship('Survey', back_populates='projects')
    users = db.relationship('User', secondary='user_project', back_populates='projects')

class Survey(db.Model):
    id_survey = db.Column(db.Integer, primary_key=True)
    start_date = db.Column(db.DateTime, nullable=False)
    end_date = db.Column(db.DateTime, nullable=False)
    name_survey = db.Column(db.String(255), nullable=False)
    #description = db.Column(db.Text, nullable=True)
    active = db.Column(db.Boolean, default=False)
    mood = db.Column(db.Integer, nullable=False)
    rating =  db.Column(db.Integer, nullable=False)
    participation = db.Column(db.Integer, nullable=False)
    id_project = db.Column(db.Integer, db.ForeignKey('project.id_project')) 
    answers = db.relationship('Survey_answer', backref='survey')
    tickets = db.relationship('Survey_ticket', backref='survey')

class Survey_answer(db.Model):
    id_survey_answer = db.Column(db.Integer, primary_key=True)
    id_survey = db.Column(db.Integer, db.ForeignKey('survey.id_survey'))
    answers = db.Column(db.String(255), nullable=False)

class Survey_ticket(db.Model):
    user_id = db.Column(db.Integer, db.ForeignKey('user.id_user'), primary_key=True)
    survey_id = db.Column(db.Integer, db.ForeignKey('survey.id_survey'), primary_key=True)
    completed = db.Column(db.Boolean, default=False)


user_project = db.Table('user_project',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id_user'), primary_key=True),
    db.Column('project_id', db.Integer, db.ForeignKey('project.id_project'), primary_key=True)
)

class Stats:
    projects = Project
    surveys = Survey
    survey = Survey
    selected_project: int
    selected_survey: int
    survey_has_answers: int
    

admin/views.py
import os
from flask import Blueprint, render_template

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/admin')
def index():
    return render_template('admin/index.html')

app.py
from flask import Flask, redirect, render_template, request, session, url_for
from flask_sqlalchemy import SQLAlchemy
from crewverve.data import get_user_by_name
from crewverve.middleware import authenticate_handler
from crewverve.views import crewverve_bp
from crewverve.models import init_app
from admin.views import admin_bp

app = Flask(__name__)

# The SECRET_KEY is used to encrypt session data in (persistent) cookies.
# >>> import secrets; secrets.token_hex(32)
app.config['SECRET_KEY'] = '642918690903c342d812d16cd33a4de4c8692483462550c9ddcd4303621cc1b2'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///crewverve.db'
# app.config['EXPLAIN_TEMPLATE_LOADING'] = True
db = init_app(app)
app.register_blueprint(crewverve_bp)
app.register_blueprint(admin_bp)

app.app_context().push()
db.create_all()


@app.before_request
def before_request():
    return authenticate_handler(None)



@app.route('/login', methods=['GET', 'POST'])
def login():
    #------V01 Paloma-----------------------------------------------
    error = None

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = get_user_by_name(username)

        if user is None or not user.check_password(password):
            error = 'Invalid username or password'
        else:
            # Note: Flask session. NOT SqlAlchemy...
            session['CURRENT_USER'] = username
            return redirect(url_for('crewverve.index'))
        
        

    return render_template('login.html', error=error)
#------V01 Paloma-----------------------------------------------


@app.route('/logout', methods=['GET'])
def logout():

    # Note: Flask session. NOT SqlAlchemy...
    del session['CURRENT_USER']
    return redirect(url_for('login'))


@app.route('/')
def index():
    return redirect(url_for('crewverve.index'))


@app.route('/page-not-found')
def page_not_found():
    return render_template('error.html', error_message="Page not found", error_description="This isn't the page you are looking for....")


if __name__ == '__main__':
    app.run(debug=True)

crewverve/views.py
from flask import Blueprint, redirect, render_template, request, session, url_for


from .data import get_survey_by_id, get_pending_surveys_by_user, questions, transform_mood, update_ticket, show_result, save_results


crewverve_bp = Blueprint('crewverve', __name__)


@crewverve_bp.route('/crewverve')
def index():
    pending_surveys = get_pending_surveys_by_user(session['CURRENT_USER'])
    return render_template('crewverve/index.html', pending_surveys=pending_surveys)


@crewverve_bp.route('/crewverve/survey', methods=['POST'])
def survey():
    id_survey = request.form['survey_id']
    survey = get_survey_by_id(id_survey)
    return render_template('crewverve/survey.html', questions=questions, survey=survey)


@crewverve_bp.route('/crewverve/results', methods=['POST'])
def results():
    """results llama a dos métodos:
    1) save_results -> inserta una respuesta y actualiza estadísticas y 
       update_ticket (da por completado un ticket por encuesta y usuario)
    """ 
    #1.1 Obtenemos datos de pantalla con request.form (survey_id, mood (transformando valores) y rating-n)
    #id_survey = request.form['id_survey']
    id_survey = request.form['survey_id']
    mood_input = transform_mood(request.form['mood'])
    rating0 = request.form['rating-0']
    rating1 = request.form['rating-1']
    rating2 = request.form['rating-2']
    rating3 = request.form['rating-3']
    rating4 = request.form['rating-4']
    rating5 = request.form['rating-5']
    rating6 = request.form['rating-6']
    rating7 = request.form['rating-7']
    #1.2 Creamos answers como un string formado por la unión de la variable mood y las 8 variables rating_input y llamamos a la función create_answer(inserta en Survey_answers) 
    answers = f'{mood_input},{rating0},{rating1},{rating2},{rating3},{rating4},{rating5},{rating6},{rating7}'
    #1.3 En resultado_save guardamos el resultado del metodo save_results (true o False). 
    # Tiene los metodos 'create_answer' y 'update_survey_stats' y update ticket
    if save_results(id_survey,answers, session['CURRENT_USER']):
        survey = get_survey_by_id(id_survey)
        return redirect(url_for('crewverve.show_results_footer', project_id=survey.id_project, survey_id=int(id_survey)))
    else:
        return render_template('error.html', error_message="error", error_description="No se ha podido grabar su respuesta, inténtelo más tarde")


@crewverve_bp.route('/crewverve/results_footer', methods=['GET'])
def show_results_footer():
    """show_results -> muestra la pantalla de estadísticas"""
    if 'project_id' in request.args:
        id_project = request.args.get('project_id',type=int)
    else:
        id_project = 0
    
    if 'survey_id' in request.args:
        id_survey = request.args.get('survey_id',type=int)
    else:
        id_survey = 0
    stat = show_result(session['CURRENT_USER'],id_project,id_survey)

    if stat == 0:
        return render_template('error.html', error_message="error", error_description="No está asignado a ningun proyecto")
    return render_template('crewverve/results.html', stats=stat)

templates/base.html
<!doctype html>
<html data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Crew-verve</title>
    <script src="https://unpkg.com/htmx.org@1.8.5"
            integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.2/dist/full.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.cdnfonts.com/css/bebas-neue" rel="stylesheet">
    <style>
        .crewverve-title {
            font-family: 'Bebas Neue', sans-serif;
        }
    </style>
</head>
<body>


 {% block content %}{% endblock %}


</body>
</html>

templates/crewverve/index.html
{% extends '/base.html' %}


{% block content %}

<div class="hero min-h-screen bg-base-200">
    <div class="hero-content flex-col lg:flex-row">
      <img src="{{ url_for('static', filename='crewverve-janus-face.png') }}" class="max-w-sm rounded-lg shadow-2xl" />
      <div>
        <h1 class="text-5xl font-bold"><span class="crewverve-title">Crew-verve</span>: tell what you feel and think</h1>
        <p class="py-6">We invite you to share what you feel and think about your current project(s). We would like to know 
          how things are going, as the Team really knows best. But people don't always feel free to share their true opinions. 
          With this application you can provide us with your feedback anonymously as the data you provide is not tracable to 
          you <sup>*)</sup>. Select a pending Survey from the select box down. Click on menuy "Results" to see the stats related
          with your projects. 
        </p>
        <p class="py-2"><sup>*)</sup> The application keeps track whether you have completed a survey but does not present that information
          to the PM. And your answers are stored without any possible association to you.</p>
        <form action="{{ url_for('crewverve.survey') }}" method="POST">
        <div class="form-control">
          <label class="input-group">
            <span>Pending surveys</span>
            <select name="survey_id" {{ 'disabled' if (pending_surveys | length) == 0 }} class="select select-primary w-full max-w-xs">
              
              {% for survey in pending_surveys %}
                  <option value="{{survey.id_survey}}">{{survey.name_survey}}</option>
              {% endfor %}
            </select>
            <button class="{{ 'btn-disabled' if (pending_surveys | length) == 0 }} btn btn-primary">Goto survey</button>
          </label>
        </div> 
        </form>  
      </div>
    </div>
   
    <div class="hidden lg:block fixed bottom-0 w-full">
        {%  include 'footer.html' %}
    </div>
  
</div>
<div class="block lg:hidden">
{%  include 'footer.html' %}
</div>

{% endblock %}

templates/crewverve/result-stats.html
<div id="stats-container" class="flex flex-col justify-center">
  <div class="flex flex-col lg:flex-row  justify-center">
    <select hx-get="{{ url_for('crewverve.show_results_footer') }}" hx-trigger="change" hx-target="#stats-container" name="project_id" class="select select-primary mb-5 w-full max-w-xs">
                
        {% for project in stats.projects %}
            <option value="{{project.id_project}}" data-debug="{{loop.index0}}{{stats.selected_project}}"  {{ 'selected' if loop.index0 == stats.selected_project }} >{{project.name_project}}</option>
        {% endfor %}
    </select>

    <select hx-get="{{ url_for('crewverve.show_results_footer') }}" hx-trigger="change" hx-target="#stats-container" name="survey_id" class="select select-primary mb-5 w-full max-w-xs">
                
      {% for survey in stats.surveys %}        
          <option value="{{survey.id_survey}}" {{'selected' if loop.index0 == stats.selected_survey}} >{{survey.name_survey}}</option>
      {% endfor %}
    </select>

  </div>

  <div class=" rounded-lg shadow-lg p-8">

    <div id="stats-container"  class="{{'hidden' if stats.selected_survey == -1}} stats shadow stats-vertical lg:stats-horizontal">
      
      <div class="stat place-items-center">
        <div class="stat-title">Rating</div>
        <div class="stat-value">
          <div class="rating {{'grayscale opacity-25' if stats.survey_has_answers == -1}}">
            <input type="radio" name="rating-5" class="mask mask-star-2 bg-blue-400" disabled {{'checked' if stats.survey.rating|round|int == 1}}/>
            <input type="radio" name="rating-5" class="mask mask-star-2 bg-blue-400" disabled {{'checked' if stats.survey.rating|round|int == 2}} />
            <input type="radio" name="rating-5" class="mask mask-star-2 bg-blue-400" disabled {{'checked' if stats.survey.rating|round|int == 3}}/> 
            <input type="radio" name="rating-5" class="mask mask-star-2 bg-blue-400" disabled  {{'checked' if stats.survey.rating|round|int == 4}}/>
            <input type="radio" name="rating-5" class="mask mask-star-2 bg-blue-400" disabled {{'checked' if stats.survey.rating|round|int == 5}}/>
          </div>
        </div>
        <div class="stat-desc">{{stats.survey.name_survey}}</div>
      </div>
      
      <div class="stat place-items-center">
        <div class="stat-title">Mood</div>
        <img class="w-32 h-32" src="{{ url_for('static', filename='emojis/mood-' + stats.survey.mood|round|int | string + '.svg') }}">
      </div>
      
      <div class="stat place-items-center">
        <div class="stat-title">Survey completed</div>
        <div class="radial-progress text-primary" style="--value:{{stats.survey.participation|round|int}};">{{"%.2f"|format(stats.survey.participation)}}%</div>
      </div>
      
    </div>
    <div class="{{'hidden' if stats.surveys|length > 0}} alert alert-warning shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
        <span>This project doesn't have any surveys</span>
      </div>
    </div>

    <div class="{{'hidden' if stats.survey_has_answers == 1}} alert alert-warning shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
        <span>This survey doesn't have any answers as yet</span>
      </div>
    </div>

  </div>

</div>

templates/crewverve/results.html
{% extends '/base.html' %}


{% block content %}


<div class="flex items-center justify-center h-screen bg-base-200">


  {% include '/crewverve/result-stats.html' %}

  <div class="hidden lg:block fixed bottom-0 w-full">
    {%  include 'footer.html' %}
  </div>
</div>


<div class="block lg:hidden">
  {%  include 'footer.html' %}
</div>

{% endblock %}

templates/crewverve/survey.html
{% extends '/base.html' %}

{% block content %}

<div class="navbar bg-base-100">
    <img class="w-10 h-10" src="{{ url_for('static', filename='crewverve-janus-face.png') }}">
    <span class="normal-case text-xl"><span class="crewverve-title font-bold text-3xl">Crew-verve</span>: tell what you feel and think (survey: {{survey.name_survey}})</span>
</div>
<form action="{{ url_for('crewverve.results') }}" method="POST">
<input type="hidden" name="survey_id" value={{survey.id_survey}}>
<div class="relative flex flex-wrap overflow-hidden py-6 ">

    <div class="card w-96 bg-base-100 shadow-xl m-2">
        <div class="card-body">

            <span class="text-lg">How do you feel about your current project? </span>
            <input name="mood" type="range" min="0" max="100" value="50" class="range" step="25"/>
            <div class="w-full flex justify-between px-2 text-3xl">
                <span>😭</span>
                <span>🙁</span>
                <span>😐</span>
                <span>😊</span>
                <span>😃</span>
            </div>
        </div>
    </div>

    {% for questions in questions %}
    <div class="card w-96 bg-base-100 shadow-xl m-2">
        <div class="card-body">
            <span class="text-lg">{{questions}}</span>
            <div class="rating rating-lg">
                <input type="radio" name="rating-{{loop.index0}}" value="1" class="mask mask-star-2 bg-green-500"/>
                <input type="radio" name="rating-{{loop.index0}}" value="2" class="mask mask-star-2 bg-green-500"/>
                <input type="radio" name="rating-{{loop.index0}}" value="3" checked class="mask mask-star-2 bg-green-500"/>
                <input type="radio" name="rating-{{loop.index0}}" value="4" class="mask mask-star-2 bg-green-500"/>
                <input type="radio" name="rating-{{loop.index0}}" value="5" class="mask mask-star-2 bg-green-500"/>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="card-actions">
    <button class="btn btn-primary">Save</button>
</div>
</form>
<div class="hidden lg:block fixed bottom-0 w-full">
    {%  include 'footer.html' %}
</div>

<div class="block lg:hidden">
    {%  include 'footer.html' %}
</div>

{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block content %}

<div class="hero min-h-screen" style="background-image: url(/static/error.jpg);">
    <div class="hero-overlay bg-opacity-60"></div>
    <div class="hero-content text-center text-neutral-content">
      <div class="max-w-md">
        <h1 class="mb-5 text-5xl font-bold veintitle">{{error_message}}</h1>
        <p class="mb-5">{{error_description}}</p>
        <a href="/" class="btn btn-sm btn-outline btn-info">Home</a>
      </div>
    </div>
  </div>

{% endblock %}

templates/footer.html
<footer class="footer items-center p-4 bg-base-300 text-neutral-content">
    <div class="items-center grid-flow-col">
        <a href="/" class="btn btn-sm btn-outline btn-info">Home</a>
        <a href="/crewverve/results_footer" class="btn btn-sm btn-outline btn-info">Show results</a>
        <a href="/admin" class="btn btn-sm btn-outline btn-info">Admin</a>
        <a href="/logout" class="btn btn-sm btn-ghost">logout</a>
    </div> 
    <div class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
        <p>Copyright © 2023</p>
        <a href="https://github.com/ThePhrontistery/crew-verve" target="_new" ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a> 
    </div>
</footer>

templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="flex justify-center items-center h-screen">
  <form class="bg-white p-10 rounded-lg shadow-lg" action="{{ url_for('login') }}" method="POST">
      
      <img class="w-10 h-10" src="{{ url_for('static', filename='crewverve-janus-face.png') }}">
      <span class="text-xl font-bold ml-auto"><span class="crewverve-title">Crew-verve</span> - Log in</span>
      
      {% if error %}
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-5" role="alert">
          <strong class="font-bold">{{ error }}</strong>
      </div>
      {% endif %}
      <div class="mb-5">
          <label class="block font-bold mb-2" for="username">Username</label>
          <input class="w-full px-3 py-2 border border-gray-300 rounded" type="text" name="username" id="username" required>
      </div>
      <div class="mb-5">
          <label class="block font-bold mb-2" for="password">Password</label>
          <input class="w-full px-3 py-2 border border-gray-300 rounded" type="password" name="password" id="password" required>
      </div>
      <div class="text-center">
          <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" type="submit">Log in</button>
      </div>
  </form>
</div>

{% endblock %}